model_name: ENUNU_夏目悠李_RMDN
version: 0.0.1
description: ENUNU用の夏目悠李歌声モデル(RMDN)
image: natsumeyuuri.bmp
author: アマノケイ
web: https://github.com/taroushirani/ENUNU
extra_files_list: ["~/data/r73_normal_tan0151lite/波音リツ単独音Ver1.5.1Lite/通常","~/data/r73_normal_tan0151lite/波音リツ単独音Ver1.5.1Lite/おまけ"]
