# Copyright (c) 2020 Ryuichi Yamamoto
# Copyright (c) 2020 oatsu
# Copyright (c) 2021 Tarou Shirani
# nnsvs/nnsvs/bin/conf/synthesys 以下にあったyamlファイルをまとめたもの。
# conf/synthesis/config.yaml から移植

## ENUNU専用のコンフィグ
# ENUNU用のレシピで学習したモデルかどうか
trained_for_enunu:        false
# Table (lyric -> phonemes) file path.
#table_path:               "dic/kana2phonemes_utf8_for_oto2lab.table"
table_path:               "dic/japanese.utf_8.table"
# bit depth of output wav file.
# 32 or 16 (recommended:32)
bit_depth:                32

defaults:
    - hydra/job_logging:  colorlog
    - hydra/hydra_logging: colorlog

verbose:                  100

# Setting for output WAV file.
sample_rate:              48000
gain_normalize:           true

# How was the model trained.
frame_period:             5
question_path:            "hed/jp_qst_crazy_mono_005-2_enunu_182D.hed"
log_f0_conditioning:      true

# Use ground truth duration or not
# if true, time-lag and duration models will not be used.
ground_truth_duration:    false


# If not empty, try to search statisics in the directory
stats_dir:                "dump/natsumeyuuri/norm"
# If not empty, try to search models in the directory
model_dir:                "exp/natsumeyuuri_jp_qst_crazy_mono_005-2_enunu_182D"

acoustic:
    question_path:        null
    checkpoint:           "latest.pth"
    in_scaler_path:       null
    out_scaler_path:      null
    # model_yaml:
    subphone_features:    coarse_coding
    relative_f0:          true
    post_filter:          true
# model config-----------------------------------
    stream_sizes:
        - 180
        - 3
        - 1
        - 15
    has_dynamic_features:
        - true
        - true
        - false
        - true
    num_windows:          3
    stream_weights:       null
    netG:
        _target_:         nnsvs.model.RMDN
        in_dim:           186
        out_dim:          199
        hidden_dim: 256
        num_layers: 2
        bidirectional: true
        dropout: 0.1
        num_gaussians: 4
        dim_wise: true
# ------------------------------------------------


duration:
    checkpoint:           "best_loss.pth"
    question_path:        null
    in_scaler_path:       null
    out_scaler_path:      null
    # model config-----------------------------------
    stream_sizes:
    - 1
    has_dynamic_features:
    - false
    stream_weights:
    - 1
    netG:
        _target_: nnsvs.model.RMDN
        in_dim: 182
        out_dim: 1
        hidden_dim: 256
        num_layers: 2
        bidirectional: true
        dropout: 0.5
        num_gaussians: 4
    # ------------------------------------------------



timelag:
    question_path:        null
    checkpoint:           "best_loss.pth"
    in_scaler_path:       null
    out_scaler_path:      null
    allowed_range:        [-20, 20]  # in frames
    allowed_range_rest:   [-40, 40]
    # model config-----------------------------------
    stream_sizes:
        - 1
    has_dynamic_features:
        - false
    stream_weights:
        - 1
    netG:
        _target_:         nnsvs.model.FeedForwardNet
        in_dim:           182
        out_dim:          1
        hidden_dim:       128
        num_layers:       2
        dropout:          0.5
    # ------------------------------------------------
